version: "3"
services:
  gitlab-bot:
    image: danger89/gitlab-bot:latest
    container_name: gitlab-bot
    restart: always
    networks:
      - gitlab_external_network
    volumes:
      - /home/username/folder/to/.env:/app/.env:ro
    ports:
      - "3013:3013"

networks:
  gitlab_external_network:
