services:
  gitlab-bot:
    image: registry.melroy.org/melroy/gitlab-bot/gitlab-bot:latest
    container_name: gitlab-bot
    restart: always
    networks:
      - gitlab_bot_external_network
    volumes:
      - /home/username/folder/to/.env:/app/.env:ro
    ports:
      - "127.0.0.1:3013:3013"

networks:
  gitlab_bot_external_network:
